const nextJest = require('next/jest')

const createJestConfig = nextJest({ dir: './' })

/** @type {import('jest').Config} */
const config = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testMatch: [
    '<rootDir>/app/**/*.spec.{ts,tsx}',
    '<rootDir>/app/**/*.test.{ts,tsx}',
    '<rootDir>/components/**/*.spec.{ts,tsx}',
    '<rootDir>/components/**/*.test.{ts,tsx}',
    '<rootDir>/lib/**/*.spec.{ts,tsx}',
    '<rootDir>/lib/**/*.test.{ts,tsx}',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  coverageDirectory: 'coverage',
  coverageReporters: ['lcov', 'text', 'clover', 'text-summary'],
  collectCoverageFrom: [
    'app/**/*.{ts,tsx}',
    'components/**/*.{ts,tsx}',
    'lib/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/layout.tsx',
    '!app/error.tsx',
    '!app/not-found.tsx',
    '!app/codeEditor/App.tsx',
    '!app/codeEditor/components/VideoCall/**',
    '!app/codeEditor/components/CollaborativeWhiteboard*.tsx',
    '!app/codeEditor/components/MonacoCanvas.tsx',
    '!app/codeEditor/components/EditorTerminal.tsx',
    '!app/codeEditor/components/EditorSidebar.tsx',
    '!app/codeEditor/components/EditorHeader.tsx',
    '!app/codeEditor/components/AIChatPanel.tsx',
    '!app/codeEditor/components/EditorTerminal.tsx',
    '!app/codeEditor/hooks/WebRTCHook/**',
    '!app/codeEditor/hooks/useSessionSocket.ts',
    '!app/codeEditor/hooks/useSessionCallData.ts',
    '!app/codeEditor/hooks/useRemoteCursorStyles.ts',
    '!app/codeEditor/hooks/useRemoteNameLabels.ts',
    '!app/codeEditor/lib/yjs*.ts',
    '!app/design/**',
    '!app/(landing)/**',
    '!app/api/**',
    '!app/auth/callback/**',
    '!lib/terminal*.tsx',
    '!lib/terminal-components/**',
    '!lib/theme/**',
    '!components/ui/animated-shader-hero.tsx',
    '!components/ui/cursor-dither-trail.tsx',
    '!components/ui/ProjectLoadingModal.tsx',
    '!components/ui/ProjectSyncProgress.tsx',
    '!components/ui/dropdown-menu.tsx',
    '!components/ui/field.tsx',
    '!components/ui/checkbox.tsx',
    '!components/theme-provider.tsx',
    '!components/mode-toggle.tsx',
  ],
}

module.exports = createJestConfig(config)
