sonar.projectKey=N3TRS_NetFrontEnd
sonar.organization=n3trs
sonar.projectName=NetFrontEnd

sonar.host.url=https://sonarcloud.io

sonar.sources=app,components,lib
sonar.tests=app,components,lib

sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/*.d.ts,.next/**,coverage/**,node_modules/**,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
